Issue 405
gems-uff/sapos pull request #463
Opened 2024-05-19 13:28 UTC by IgorMonardez

Nessa Issue eu entendi desse jeito, como todo e-mail respondido iria para a adm da sapos, que eu supus ser sapos@sapos.ic.uff.br, todo e-mail respondido pelo usuário iria para ele e teria ainda outra reply_to definida via variável do usuário.

2024-05-19 20:05 UTC, JoaoFelipe commented
O template de email deveria carregar o email padrão de CustomVariables ao invés de usar sapos@sapos.ic.uff.br hardcoded.
Além disso, seria bom alterar também o mailer para usar o reply_to


Não cheguei a olhar a fundo a parte de notification_logs que foi alterada. Não sei se tem muita necessidade de armazenar o reply_to, mas não vejo problema em ter.

2024-05-20 14:14 UTC, IgorMonardez commented
Portanto o email ***@***.*** entraria como seed do projeto na
CustomVariable?
*Igor Monárdez*

*Estudante de Ciência da Computação UFF*

Em dom., 19 de mai. de 2024 às 17:06, João Felipe N. Pimentel <
***@***.***> escreveu:

> O template de email deveria carregar o email padrão de CustomVariables ao
> invés de usar ***@***.*** hardcoded.
> Além disso, seria bom alterar também o mailer para usar o reply_to
>
> Não cheguei a olhar a fundo a parte de notification_logs que foi alterada.
> Não sei se tem muita necessidade de armazenar o reply_to, mas não vejo
> problema em ter.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gems-uff/sapos/pull/463#issuecomment-2119345402>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU3E3EUFRMXYACEWMF5KZXLZDEA25AVCNFSM6AAAAABH6MA6CCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJZGM2DKNBQGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-22 18:57 UTC, JoaoFelipe requested changes
Adicionei comentários com sugestões de mudanças nas linhas alteradas.

2024-05-22 18:57 UTC, JoaoFelipe commented on db/migrate/20240517150433_add_reply_to_to_notification_logs.rb
> +  def change
Aqui deveria ser down, não?

Tentei executar a migração e não criou o reply_to em NotificationLogs, inclusive dando erro quando tentei executar uma notificação

2024-05-22 18:57 UTC, JoaoFelipe commented on app/models/custom_variable.rb
> +    config.blank? ? nil : (config.value || "")
Que tal colocar o valor "sapos@sapos.ic.uff.br" como padrão do método CustomVariable.reply_to? Isso tiraria a necessidade dos diversos `unless CustomVariable.reply_to.blank?`

O seeds só é usado como uma nova instância é criada e tem mais de uma instância sendo usada.

E note que o padrão no application.rb já é usar este email, então não ter a possibilidade de deixar em branco não muda o comportamento.

2024-05-22 18:57 UTC, JoaoFelipe commented on app/models/email_template.rb
> +        template.reply_to = CustomVariable.reply_to unless CustomVariable.reply_to.blank?
Se seguir a sugestão do valor padrão, o unless não é necessário

2024-05-22 18:57 UTC, JoaoFelipe commented on app/models/email_template.rb
> +    headers[:reply_to] = CustomVariable.reply_to unless CustomVariable.reply_to.blank?
Se seguir a sugestão do valor padrão, o unless não é necessário

2024-05-22 18:57 UTC, JoaoFelipe commented on db/seeds.rb
> +  { description: "E-mail das resposta de emails automáticos", variable: "reply_to", value: "sapos@sapos.ic.uff"},
Falta o .br

2024-05-22 18:57 UTC, JoaoFelipe commented on app/mailers/devise_mailer.rb
> +      inline: @template.reply_to
Ao invés de termos reply_to no EmailTemplate, acho melhor sempre acessar de CustomVariable. A não ser que tenha a opção de editar o reply_to na interface do template e isso seja algo opcional.

Da forma que está, se EmailTemplate for salvo com um reply_to específico (carregado automaticamente de CustomVariable, já que não há opção de editar) e o CustomVariable mudar, o valor que está em EmailTemplate provavelmente não vai mudar e vai causar um bug.

2024-05-22 18:57 UTC, JoaoFelipe commented on db/migrate/20240519124956_add_reply_to_to_email_templates.rb
> +end
Se seguir a sugestão de não ter reply_to em EmailTemplate, essa migration não é necessária.

2024-05-22 19:25 UTC, IgorMonardez commented on app/models/custom_variable.rb
> +    config.blank? ? nil : (config.value || "")
Eu utilizei os unless pelo fato de manter o sistema rodando como estava antes, de acordo com a colocação do professor Leo Murta nas resposta da ISSUE.

2024-05-22 19:31 UTC, IgorMonardez commented on db/migrate/20240517150433_add_reply_to_to_notification_logs.rb
> +  def change
Não consegue executar a notificação mesmo consertando a migração, ou pq a migração não funcionou por conta desse erro do down + change

2024-05-22 19:59 UTC, JoaoFelipe commented on db/migrate/20240517150433_add_reply_to_to_notification_logs.rb
> +  def change
Não cheguei a tentar corrigir para testar, mas a migração rodou (sem criar o reply_to - ou criando pelo up e removendo logo em seguida pelo change) e só percebi o problema porque deu o erro em NotificationLogs e tentei dar rollback: deu erro no rollback.

2024-05-22 19:59 UTC, JoaoFelipe commented on app/models/custom_variable.rb
> +    config.blank? ? nil : (config.value || "")
Sim, o unless em si não tem o problema e essa sugestão é só de estilo - não precisa alterar se achar que não faz sentido.

O ponto da sugestão é que se colocar o valor padrão aqui, o sistema continua funcionando da forma que estava antes e concentra a verificação do valor existir ou não neste único método. Pensando bem, uma solução ainda melhor do que ter o valor hardcoded aqui seria ter valor padrão como `ActionMailer::Base::default[:reply_to] || ActionMailer::Base::default[:from]`.

2024-05-24 12:45 UTC, IgorMonardez commented on db/migrate/20240517150433_add_reply_to_to_notification_logs.rb
> +  def change
![image](https://github.com/gems-uff/sapos/assets/87444882/da8ffeb1-ebce-4cad-b623-5d057057abda)

Estou conseguindo executar a notificação localmente

2024-05-24 13:28 UTC, IgorMonardez commented
Fiz mais um push relacionado a esse pull request

2024-05-27 21:40 UTC, merged