Adds QR code signatures when config is enabled
gems-uff/sapos pull request #475
Opened 2024-06-05 16:22 UTC by anderson-mj

2024-09-23 12:04 UTC, caiovelp commented on app/uploaders/pdf_uploader.rb
> +      local_file = FilelessIO.new(Base64.decode64(file[:base64_contents]))
Será que não vale a pena fazer uma tratativa de erro aqui?

2024-09-23 12:05 UTC, caiovelp commented on app/uploaders/pdf_uploader.rb
Talvez validar que o arquivo fazendo upload aqui seja um PDF? O que acontece se o cara tenta fazer upload de qualquer outra extensão?

2024-09-23 12:09 UTC, caiovelp requested changes
Deixei alguns comentários, depois dá uma analisada

2024-09-26 18:03 UTC, caiovelp approved these changes

2024-10-01 19:33 UTC, anderson-mj commented on app/uploaders/pdf_uploader.rb
> +      local_file = FilelessIO.new(Base64.decode64(file[:base64_contents]))
Esse arquivo vai ser refatorado quando o upload pelo site realmente acontecer, atualmente só é usado pra salvar o arquivo binário no BD.

2024-10-01 19:34 UTC, anderson-mj commented on app/uploaders/pdf_uploader.rb
Esse arquivo vai ser refatorado quando o upload pelo site realmente acontecer, atualmente só é usado pra salvar o arquivo binário no BD.

2024-10-02 15:08 UTC, merged