Declarações customizáveis
gems-uff/sapos pull request #508
Opened 2024-12-09 21:50 UTC by caiovelp

2024-12-11 05:03 UTC, JoaoFelipe requested changes
Ainda não executei para conferir, mas coloquei alguns comentários

2024-12-11 05:03 UTC, JoaoFelipe commented on spec/models/assertion_spec.rb
> +      assoc = described_class.reflect_on_association(:query)
Dá uma olhada nos tests dos outros modelos. Dá pra simplificar esse teste.
Além disso, faltam testes de outras validações e falta o factory

2024-12-11 05:03 UTC, JoaoFelipe commented on config/locales/assertion.pt-BR.yml
> +        one: "Documento"
Por consistência, deveria ser "Declaração"

2024-12-11 05:03 UTC, JoaoFelipe commented on config/locales/pt-BR.yml
> +  date:
Temos esses formatos de datas em datetime.pt-BR.yml. Você viu alguma necessidade de redefinir aqui?

2024-12-12 23:03 UTC, caiovelp commented on config/locales/pt-BR.yml
> +  date:
Quando fiz acho que a data na declaração tava saindo com um formato estranho, mas aparentemente agora tá normal (Sem essa parte)

2025-01-06 23:41 UTC, JoaoFelipe commented
A geração de "Declaração de relatório de disciplinas para aluno avulso" está com um problema aqui:

![image](https://github.com/user-attachments/assets/7995244d-7306-469f-b9fb-b87c358a1cf6)

O template parece certo:

```
DECLARAÇÃO

        Declaro, para os devidos fins, que <%= var('nome_aluno') %> cursou como Aluno Avulso as seguintes disciplinas do Programa de Pós-Graduação em Computação, nos termos do Art. 15 do Regulamento dos Programas de Pós-Graduação Stricto Sensu da Universidade Federal Fluminense.

        <% records.each do |record| %>
          <%= record['counter'] %>. Nome da disciplina: "<%= record['nome_disciplina'] %>"
          Carga horaria total: <%= record['carga_horaria'] %>
          Período: <%= var('ano_disciplina') %>/<%= var('semestre_disciplina') %>
          Nota: <%= record['nota'] %>
          Situação final: <%= record['situacao'] %>
        <% end %>
```


Fui investigar o código e parece que ao invés de usar o sistema de templates da notificação, as declarações foram implementadas com regex (função `replace_placeholders` de `assertions_pdf_helpers.rb`

Será que você não consegue usar o ERB formatter para deixar o sistema mais flexível que regex?

Se usar ERB formatter, não acho que vai ser necessário ter o `record['counter']`: ao invés disso, dá pra fazer a iteração com `each_with_index`.

2025-01-07 01:18 UTC, JoaoFelipe commented
Acho que seria interessante ter uma forma de definir qual a forma de assinatura por declaração, mas talvez seja melhor deixar estabilizar esse PR e deixar isso pra uma issue futura.

2025-01-07 01:25 UTC, JoaoFelipe requested changes

2025-01-07 01:25 UTC, JoaoFelipe commented on app/helpers/assertions_pdf_helper.rb
> +    values['cpf_aluno'] = mask_cpf(values['cpf_aluno']) if values.key?('cpf_aluno')
Usando o ERBFormatter, será que não faria sentido ter o mask_cpf como uma função helper dele (assim como existe o localize)?

2025-01-07 01:25 UTC, JoaoFelipe commented on app/helpers/assertions_pdf_helper.rb
> +    values['data'] = format_date(Date.parse(values['data'])) if values.key?('data')
Mesma coisa aqui. Esse format_date poderia ser um helper no ERBFormatter

Aliás, precisamos disso separado? Será que o localize não atende?

2025-01-07 01:25 UTC, JoaoFelipe commented on app/views/queries/_sql_form_column.html.erb
> +          <li>Caso queira usar uma variável de data e formatá-la por extenso, identifique-a como ¨data¨</li>
Se for fazer as alterações que sugeri, remova essa linha.

Se não fizer, é necessário que o comportamento seja replicado pra notificações, já que a consulta serve pra ambos

2025-01-08 03:40 UTC, caiovelp commented on app/helpers/assertions_pdf_helper.rb
> +    values['cpf_aluno'] = mask_cpf(values['cpf_aluno']) if values.key?('cpf_aluno')
Por enquanto vou remover essa função, pois das declarações que fiz por padrão, nenhuma usa o CPF, e depende tb do nome da variável.

2025-01-08 03:40 UTC, caiovelp commented on app/helpers/assertions_pdf_helper.rb
> +    values['data'] = format_date(Date.parse(values['data'])) if values.key?('data')
Atende sim!

2025-01-15 01:01 UTC, merged